## IBM HR DATASET scaling and encoding

In [ ]:
# Raw IBM HR Dataset
#         ↓
# EDA
#         ↓
# Remove unnecessary columns
# (EmployeeCount, EmployeeNumber, Over18, StandardHours)
#         ↓
# Separate X and y
#         ↓
# Train-Test Split
#         ↓
# Identify feature types
#         ↓
# ┌─────────────────────────────┐
# │ Continuous Numerical        │ → StandardScaler
# │ Ordinal Numerical            │ → StandardScaler
# │ Categorical / Nominal        │ → OneHotEncoder
# └─────────────────────────────┘
#         ↓
# ColumnTransformer
#         ↓
# fit_transform(X_train)
#         ↓
# transform(X_test)
#         ↓
# 51 processed features
#         ↓
# Convert to DataFrame

In [12]:
import pandas as pd
import numpy as np

In [13]:
df = pd.read_csv(r"employee_attrition.csv")

# EDA

In [14]:
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   object
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   object
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1470 non-null   object
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   object
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1470 non-null   object
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   object
 22  OverTime                  1470 non-null   object
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   int64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(26), object(9)
memory usage: 402.1+ KB

In [16]:
df.describe()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
count,1470.000000,1470.000000,1470.000000,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,...,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000
mean,36.923810,802.485714,9.192517,2.912925,1.0,1024.865306,2.721769,65.891156,2.729932,2.063946,...,2.712245,80.0,0.793878,11.279592,2.799320,2.761224,7.008163,4.229252,2.187755,4.123129
std,9.135373,403.509100,8.106864,1.024165,0.0,602.024335,1.093082,20.329428,0.711561,1.106940,...,1.081209,0.0,0.852077,7.780782,1.289271,0.706476,6.126525,3.623137,3.222430,3.568136
min,18.000000,102.000000,1.000000,1.000000,1.0,1.000000,1.000000,30.000000,1.000000,1.000000,...,1.000000,80.0,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,30.000000,465.000000,2.000000,2.000000,1.0,491.250000,2.000000,48.000000,2.000000,1.000000,...,2.000000,80.0,0.000000,6.000000,2.000000,2.000000,3.000000,2.000000,0.000000,2.000000
50%,36.000000,802.000000,7.000000,3.000000,1.0,1020.500000,3.000000,66.000000,3.000000,2.000000,...,3.000000,80.0,1.000000,10.000000,3.000000,3.000000,5.000000,3.000000,1.000000,3.000000
75%,43.000000,1157.000000,14.000000,4.000000,1.0,1555.750000,4.000000,83.750000,3.000000,3.000000,...,4.000000,80.0,1.000000,15.000000,3.000000,3.000000,9.000000,7.000000,3.000000,7.000000
max,60.000000,1499.000000,29.000000,5.000000,1.0,2068.000000,4.000000,100.000000,4.000000,5.000000,...,4.000000,80.0,3.000000,40.000000,6.000000,4.000000,40.000000,18.000000,15.000000,17.000000

# Data Preprocessing

## train_test_split

In [26]:
from sklearn.model_selection import train_test_split

In [28]:
x = df.drop("Attrition" , axis=1)
y = df['Attrition']

In [29]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3, random_state=42)

In [30]:
for col in df.columns:
    print(f"{col}: {df[col].nunique()} unique values")

Age: 43 unique values
Attrition: 2 unique values
BusinessTravel: 3 unique values
DailyRate: 886 unique values
Department: 3 unique values
DistanceFromHome: 29 unique values
Education: 5 unique values
EducationField: 6 unique values
EmployeeCount: 1 unique values
EmployeeNumber: 1470 unique values
EnvironmentSatisfaction: 4 unique values
Gender: 2 unique values
HourlyRate: 71 unique values
JobInvolvement: 4 unique values
JobLevel: 5 unique values
JobRole: 9 unique values
JobSatisfaction: 4 unique values
MaritalStatus: 3 unique values
MonthlyIncome: 1349 unique values
MonthlyRate: 1427 unique values
NumCompaniesWorked: 10 unique values
Over18: 1 unique values
OverTime: 2 unique values
PercentSalaryHike: 15 unique values
PerformanceRating: 2 unique values
RelationshipSatisfaction: 4 unique values
StandardHours: 1 unique values
StockOptionLevel: 4 unique values
TotalWorkingYears: 40 unique values
TrainingTimesLastYear: 7 unique values
WorkLifeBalance: 4 unique values
YearsAtCompany: 37 unique values
YearsInCurrentRole: 19 unique values
YearsSinceLastPromotion: 16 unique values
YearsWithCurrManager: 18 unique values

In [ ]:
# 1. Continuous numerical columns → Scale

# These represent quantities where numerical distance makes sense.

# Examples:

# Age
# DailyRate
# DistanceFromHome
# HourlyRate
# MonthlyIncome
# MonthlyRate
# TotalWorkingYears
# YearsAtCompany
# YearsInCurrentRole
# YearsSinceLastPromotion
# YearsWithCurrManager

# For example:

# Age: 25 → 26
# Age: 25 → 35

# The numerical difference has meaning.

# These are candidates for:

# StandardScaler()
# 2. Categorical columns → Encode

# These represent categories rather than quantities.

# For example:

# BusinessTravel
# Department
# EducationField
# Gender
# JobRole
# MaritalStatus
# OverTime

# Consider:

# Gender:
# Male
# Female

# We cannot give:

# Male = 1
# Female = 2

# and pretend that 2 > 1 has meaningful mathematical significance.

# So we use encoding.

# For nominal categorical variables, we'll generally use:

# OneHotEncoder()

# For example:

# Department

# Sales
# HR
# Research & Development

# becomes something conceptually like:

# Department_HR
# Department_Research & Development
# Department_Sales
# 3. Integer columns that LOOK numerical but aren't necessarily continuous

# This is the interesting part.

# Look at:

# Education: 5 unique values
# JobLevel: 5 unique values
# JobSatisfaction: 4 unique values
# PerformanceRating: 2 unique values

# They're int64, but they represent levels/ratings, not normal continuous measurements.

# For example:

# JobSatisfaction

# 1 = Low
# 2 = Medium
# 3 = High
# 4 = Very High

# The numbers represent ordered categories.

# This is called ordinal data.

# So we shouldn't automatically say:

# if dtype == "int64":
#     StandardScaler()

# because that would treat every integer column as continuous.

# Now look at these
# EmployeeCount: 1 unique value
# Over18: 1 unique value
# StandardHours: 1 unique value

# They have zero variation.

# For example:

# EmployeeCount

# 1
# 1
# 1
# 1
# 1
# ...

# There is nothing useful for a model to learn from this column.

# So these are candidates for removal.

# And this one is special
# EmployeeNumber: 1470 unique values

# You have 1470 employees and 1470 employee numbers.

# That means:

# EmployeeNumber
# 1001
# 1002
# 1003
# ...

# is essentially an identifier, not a meaningful feature.

# We shouldn't scale it just because it's an integer.

# So we'd normally remove it too.

# This is the main lesson

# Your dataset is teaching you something very important:

#                     Data Type
#                        ↓
#                  Is it enough?
#                        ↓
#                       NO
#                        ↓
#              Understand the column
#                        ↓
#        ┌───────────────┼────────────────┐
#        ↓               ↓                ↓
#   Continuous       Categorical       Identifier/
#    numerical        / Ordinal         Constant
#        ↓               ↓                ↓
#     Scaling          Encoding         Remove

# This is much more professional than simply doing:

# numerical_cols = df.select_dtypes(include="number").columns
# categorical_cols = df.select_dtypes(include="object").columns

# That method is useful as a starting point, but it can make mistakes when integer columns represent categories, ratings, IDs, or constants.

## column classifiatoin

Before column treansformation


columns to remove:

* EmployeeCount

* Over18

* StandardHours
* EmployeeNumber

In [35]:
drop_cols = ["EmployeeCount", "EmployeeNumber" , "Over18" , "StandardHours"]
numerical_columns = [ "Age",
    "DailyRate",
    "DistanceFromHome",
    "HourlyRate",
    "MonthlyIncome",
    "MonthlyRate",
    "NumCompaniesWorked",
    "PercentSalaryHike",
    "TotalWorkingYears",
    "TrainingTimesLastYear",
    "YearsAtCompany",
    "YearsInCurrentRole",
    "YearsSinceLastPromotion",
    "YearsWithCurrManager"]

# added later

ordinal_cols = [
    "Education",
    "EnvironmentSatisfaction",
    "JobInvolvement",
    "JobLevel",
    "JobSatisfaction",
    "PerformanceRating",
    "RelationshipSatisfaction",
    "StockOptionLevel",
    "WorkLifeBalance"
]




categorical_columns = ["BusinessTravel",
    "Department",
    "EducationField",
    "Gender",
    "JobRole",
    "MaritalStatus",
    "OverTime"]
x_train = x_train.drop(columns = drop_cols)
x_test = x_test.drop(columns = drop_cols)

we did not include the ordinal columns, and ColumnTransformer by default drops columns that aren't specified in a transformer.

In [ ]:
# Education
# EnvironmentSatisfaction
# JobInvolvement
# JobLevel
# JobSatisfaction
# PerformanceRating
# RelationshipSatisfaction
# StockOptionLevel
# WorkLifeBalance


# A column can be numerical in storage (int64) but ordinal in meaning.

These columns are ordinal + numerical + discrete, so we should not treat them like ordinary continuous measurements, and we should not one-hot encode them by default.

we will decide later what to do whit this

## column transformation

In [ ]:
  #  X_train
  #                   │
  #                   ▼
  #         ┌───────────────────┐
  #         │ ColumnTransformer │
  #         └───────────────────┘
  #            │             │
  #            ▼             ▼
  #      Numerical        Categorical
  #         │                  │
  #         ▼                  ▼
  # StandardScaler      OneHotEncoder
  #         │                  │
  #         └────────┬─────────┘
  #                  ▼
  #         Processed X_train

In [ ]:
# Why handle_unknown="ignore"?

# Suppose the training data contains:

# JobRole
# Sales Executive
# Research Scientist
# Manager

# but the test data happens to contain a category that wasn't present in training.

# Without handle_unknown="ignore", the encoder can produce an error.

# With:

# handle_unknown="ignore"

# it safely handles unseen categories.

# This is a common choice in production preprocessing pipelines.

In [34]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

In [54]:
preprocessor = ColumnTransformer(transformers=[
    ("num" , StandardScaler() , numerical_columns),
    ("ord", StandardScaler(), ordinal_cols),  #added later
    ("cat" , OneHotEncoder(handle_unknown="ignore") , categorical_columns)
])

x_train_processed = preprocessor.fit_transform(x_train)
x_test_processed = preprocessor.transform(x_test)

In [58]:
x_train_processed.shape

(1029, 51)

In [59]:
x_test_processed.shape

(441, 51)

## current structure

In [ ]:
# X_train / X_test
#        │
#        ├── 4 columns removed
#        │
#        ├── 14 numerical columns
#        │        ↓
#        │   StandardScaler
#        │
#        ├── 7 categorical columns
#        │        ↓
#        │   OneHotEncoder
#        │
#        └── 9 ordinal columns
#                 ↓
#              Leave for now

## processed data into df

Because X_train_processed is usually a NumPy array/sparse matrix, let's first convert it into a DataFrame with proper feature names:

In [60]:
feature_names = preprocessor.get_feature_names_out()

In [61]:
x_train_processed_df = pd.DataFrame(
    x_train_processed,
    columns = feature_names,
    index = x_train.index
)

In [62]:
x_test_processed_df = pd.DataFrame(
    x_test_processed,
    columns = feature_names,
    index = x_test.index
)

In [63]:
x_train_processed_df.head()

,num__Age,num__DailyRate,num__DistanceFromHome,num__HourlyRate,num__MonthlyIncome,num__MonthlyRate,num__NumCompaniesWorked,num__PercentSalaryHike,num__TotalWorkingYears,num__TrainingTimesLastYear,...,cat__JobRole_Manufacturing Director,cat__JobRole_Research Director,cat__JobRole_Research Scientist,cat__JobRole_Sales Executive,cat__JobRole_Sales Representative,cat__MaritalStatus_Divorced,cat__MaritalStatus_Married,cat__MaritalStatus_Single,cat__OverTime_No,cat__OverTime_Yes
714,1.413691,0.794212,-1.017728,-0.033242,2.284799,-1.077670,2.531721,1.839399,2.648882,-1.389417,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
135,-0.098346,-1.440722,-0.409362,0.846345,-0.314845,-1.613426,1.335055,1.293547,-0.534305,-2.168975,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
1271,-1.718387,-1.143549,-0.287688,-1.743551,-0.786862,-1.366719,-0.659387,-0.616935,-1.298270,0.169700,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
477,1.413691,1.088928,-0.774382,1.579335,2.451946,-0.882336,-0.659387,-1.162787,2.648882,-0.609859,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
806,1.629697,0.470024,-0.287688,0.992943,0.833690,0.151210,1.733944,1.020621,0.866297,0.949258,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0

In [51]:
feature_names

array(['num__Age', 'num__DailyRate', 'num__DistanceFromHome',
       'num__HourlyRate', 'num__MonthlyIncome', 'num__MonthlyRate',
       'num__NumCompaniesWorked', 'num__PercentSalaryHike',
       'num__TotalWorkingYears', 'num__TrainingTimesLastYear',
       'num__YearsAtCompany', 'num__YearsInCurrentRole',
       'num__YearsSinceLastPromotion', 'num__YearsWithCurrManager',
       'cat__BusinessTravel_Non-Travel',
       'cat__BusinessTravel_Travel_Frequently',
       'cat__BusinessTravel_Travel_Rarely',
       'cat__Department_Human Resources',
       'cat__Department_Research & Development', 'cat__Department_Sales',
       'cat__EducationField_Human Resources',
       'cat__EducationField_Life Sciences',
       'cat__EducationField_Marketing', 'cat__EducationField_Medical',
       'cat__EducationField_Other',
       'cat__EducationField_Technical Degree', 'cat__Gender_Female',
       'cat__Gender_Male', 'cat__JobRole_Healthcare Representative',
       'cat__JobRole_Human Resources',
       'cat__JobRole_Laboratory Technician', 'cat__JobRole_Manager',
       'cat__JobRole_Manufacturing Director',
       'cat__JobRole_Research Director',
       'cat__JobRole_Research Scientist', 'cat__JobRole_Sales Executive',
       'cat__JobRole_Sales Representative', 'cat__MaritalStatus_Divorced',
       'cat__MaritalStatus_Married', 'cat__MaritalStatus_Single',
       'cat__OverTime_No', 'cat__OverTime_Yes'], dtype=object)

In [52]:
len(feature_names)

42

## remainig columns

In [ ]:
# Education                 → Ordinal, discrete
# EnvironmentSatisfaction   → Ordinal, discrete
# JobInvolvement            → Ordinal, discrete
# JobLevel                  → Ordinal, discrete
# JobSatisfaction           → Ordinal, discrete
# PerformanceRating         → Ordinal, discrete
# RelationshipSatisfaction  → Ordinal, discrete
# StockOptionLevel          → Ordinal, discrete
# WorkLifeBalance           → Ordinal, discrete

In [53]:
ordinal_cols = [
    "Education",
    "EnvironmentSatisfaction",
    "JobInvolvement",
    "JobLevel",
    "JobSatisfaction",
    "PerformanceRating",
    "RelationshipSatisfaction",
    "StockOptionLevel",
    "WorkLifeBalance"
]

now we will add this in ColumnTransformation and scale it for now this project

In [ ]:
# Feature type	 -->                      Typical treatment
# Continuous numerical -->	                 StandardScaler
# Ordinal numerical -->               	Keep numeric/ordinal, optionally scale
# Nominal categorical	 -->                  OneHotEncoder